version: '3'

services:
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./web:/usr/share/nginx/html:ro"
