version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - "./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./front/public:/usr/share/nginx/html/public"
    ports:
      - "8000:80"
    restart: always
    depends_on:
      - python
    command: ["nginx-debug", "-g", "daemon off;"]
  python:
    build:
      context: .
      dockerfile: Dockerfile.python
    expose:
      - "3031"
    volumes:
      - "./back:/usr/src/back"
    command: /bin/bash -c "uwsgi --ini /usr/src/back/uwsgi.ini"
