version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    volumes:
      - "./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./front/public:/usr/share/nginx/html/public"
    depends_on:
      - flask
  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
    expose:
      - "3031"
    volumes:
      - "./back:/usr/share/nginx/html"
    command: /bin/bash -c "uwsgi --ini /usr/share/nginx/html/uwsgi.ini"
