version: '3'

services:
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro"
    depends_on:
      - flask
  flask:
    build: 
      context: ./flask
    expose:
      - "3031"
    volumes:
      - "./flask:/usr/src/app"
    command: /bin/bash -c "uwsgi --ini /usr/src/app/uwsgi.ini"
